### PR TITLE
Fixed bug where potion effect times were not being changed

### PR DESCRIPTION
**Pull request by soerxpso**

### CODE REVIEW

**Comment by rourke750** [comment]
Can you sign the clahub.

Also does this fix the issue with the clients being kicked from invalid packets?

**Comment by soerxpso** [comment]
I'm not sure if this fixes the issue with clients being kicked from invalid packets. Do you know how I could reproduce that bug to check?

**Comment by rourke750** [comment]
Get a few accounts on, move around, hit each other, have enchantments on.  Its kind of random.

**Comment by soerxpso** [comment]
Alright, well I just tried that and didn't notice any problems. I can't say for sure that I didn't just get lucky though. More extensive testing is probably necessary. ShadedJon was planning on getting this running on Devoted, so I'll let you know if any problems happen there.

**Comment by ttk2** [comment]
that sounds good, hopefully we can get this running well.

**Comment by ProgrammerDan** [comment]
Awesome, hero man. I think what we can do is put this on Devoted and run a PVP event, perhaps this weekend or next. That should give us enough combat to see if it starts blowing its stack, and if so I should have tons of console log data to share.

**Comment by Squeenix** [comment]
With the armour enchantments issue you might want to try updating ProtocolLib to 3.6.5
3.40 is set as a dependency in Maven and apparently has a lot of compatibility issues.

I did some (very limited local testing) and have no issue with on 1.89 and ProtocolLib 3.6.5.

**Comment by drjawa** [comment]
I will be so pleased if this works as intended.

**Comment by ProgrammerDan** [comment]
FWIW Devoted runs using plib 3.6.5; but the version of attrhider was compiled against 3.4. I'll give a new-compile a try in the near future.

If you guys have the equipment to test out the protection this is meant to provide, I can point you at devoted's test server.

**Pull request merged**
